### ISSUE TITLE
Contentful importer: Error message with insufficient API permissions

### ISSUE THREAD

**Issue by arcataroger** [datocms/js-datocms-client#119]
Hey there,

Minor issue, but when I tried to import a space from Contentful, I got the following error:

>   ApiException: 422 INVALID_ATTRIBUTES (details: {"extraneous_attributes":["locales"]})

Turns out this was because I created a new API key in Dato but didn't give it the right permissions. (I didn't want to use the default "Full Permissions" key and have that logged to my command line history.) Using the full permission key DOES work. But using a new API key with access to the Content Management API, with user role Editor, did NOT work. It's possible the Admin role does work; I don't know what specifically controls locales.

I think this is functioning as designed, really, but maybe a more helpful error message would be nice? Like "Couldn't create locale in DatoCMS. Does your API key have the right permissions? It needs ______."

**Comment by souljuse** [comment]
Hi @arcataroger, thanks for reporting this! 

Usually permissions-related errors give back proper error messages, so this could be due to something else. 🤔 Could you write to our [support team](https://www.datocms.com/support) with the full command you are executing (--datoCmsToken, --contentfulToken and --contentfulSpaceId), so we can reproduce the issue more easily?

Thanks!

**Comment by souljuse** [comment]
Fixed! 

Now if one tries to update a site object, without the proper permissions, gets a `401 INSUFFICIENT_PERMISSIONS` error.
