### ISSUE TITLE
Invalid character error IE & ios

### ISSUE THREAD

**Issue by VitalijPetras** [datocms/js-datocms-client#25]
I am getting trouble with error. After importing datocms-client i get this error in IE11 "invalid character".

![screen-1](https://user-images.githubusercontent.com/29103850/50002895-fd57b000-ffa1-11e8-81c1-8cc7a3c42cd3.png)

After commenting out code with datocms all is working fine.

I am using gatsbyjs.

Any idea?

**Comment by matjack1** [comment]
I'm very sorry @VitalijPetras for the long delay in getting back to you.

But are you using our https://github.com/datocms/gatsby-source-datocms ?

Meanwhile we've drastically updated the plugin, so if this error is still relevant to you can you please try with the new version and reopen an issue in that project?

Otherwise I need more info on your setup (ideally access to your repo). If you prefer you can contact me at support@datocms.com

Thanks!

**Comment by VitalijPetras** [comment]
I am dont have an issue with gatsby-source-datocms. Its working fine. I have issue when i need to update datocms with https://github.com/datocms/js-datocms-client. This package is throwing error in IE. So i removed it and replaced with fetch and http requests...

**Comment by matjack1** [comment]
I see @VitalijPetras thanks for getting back to me!

Do you still have some code that I could use to replicate the issue?
