### ISSUE TITLE
Uploads don't seem to work VIA the content management API

### ISSUE THREAD

**Issue by anthonysapp** [datocms/js-datocms-client#27]
I can successfully create an upload by getting permission:
https://www.datocms.com/content-management-api/#upload_request-0

And creating an upload:
https://www.datocms.com/content-management-api/#upload-2

I get a valid upload Id returned, but the upload shows up as an empty image in the media library.

I assume I need to actually manually upload the file to the S3 url provided by the upload permission request, but I keep getting 403 errors when I try something like:

```js
// get upload permission
let req = await client.uploadRequest
      .create({
        filename
      })
      .catch(error => {
        console.log(error);
      });

// send upload
fs.createReadStream(path.resolve(__dirname, filename)).pipe(
    request.put(req.url, {
        headers: {
            'Content-Type': 'image/png'
        }
    })
);
```

Any examples of how to do this?

**Comment by matjack1** [comment]
I would say that if you don't have a specific reason you should use the `client.uploadImage` / `client.uploadFile` functions that are more straightforward.

You just do: `client.uploadImage(filename)` and it works :)

Otherwise if you want to understand more about the S3 upload you can have a look at the internals of the JS client: https://github.com/datocms/js-datocms-client/blob/master/src/upload/adapters/nodeLocal.js
