### ISSUE TITLE
SVGs Uploaded as Plain Text

### ISSUE THREAD

**Issue by wkentdag** [datocms/js-datocms-client#34]
I'm using the `SiteClient` to seed my CMS with values from a spreadsheet. When I upload a PNG it works just fine. No error is thrown when I upload an SVG, however, when I try to access it from the upload URL, it appears as `Content-type: text/html` and is unusable. It also is not visible as a preview in the CMS. It works fine after I manually upload.

Dependencies:

```
    "datocms-client": "0.8.15",
```

My code:
```js
    const newImageId = await client.uploadImage(url);
```

Source image: `https://picturestart.dev.stinkstudios.la/static/images/partners/Bron_Logo.svg`

Error in browser:
```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.datocms-assets.com/10992/1555085121-bronlogo.svg with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Comment by matjack1** [comment]
Sorry, I cannot reproduce, I've tried with another SVG ( https://www.datocms-assets.com/249/1557836703-star.svg ) and it worked.

I cannot access your SVG instead, it gives me a 401. Can you please share the image in another way?

I'm going to close now, but feel free to open again if you can reproduce again or if you can provide more info.

**Comment by timvandevelde-voormedia** [comment]
I'm using the Ruby gem to upload images. Images uploaded by content API have the CORB issue in Chrome. Manually uploaded images do not. 

https://huisdepinto.netlify.com/nieuws/

Center card background is manually uploaded. The others with the client. (WIP, content might change)

**Comment by eddyh** [comment]
To add on @timvandevelde-voormedia message:

This image is uploaded via the website and returns an `image/jpeg` content type (display in browser with Chrome):
https://www.datocms-assets.com/15059/1565721602-1-elbohemio-sfeerplaat.jpg

This image was uploaded via the API and returns an `application/x-www-form-urlencoded` content type (displays as download in Chrome):
https://www.datocms-assets.com/15059/1565718236-8u1u6l92s4zaterdag21zondag22junibrdagvandearchitectuuramsterdam591.jpg

When displaying the images on a website, the second won't work in Chrome (CORB issue).

We're not sure if the issue is in the API libraries as we were using Ruby and this issue is reported for JS. This might indicate the issue lies in the Dato API/backend. If we need to file this elsewhere, please let us know!
