### ISSUE TITLE
Updating record meta fields does not work as expected

### ISSUE THREAD

**Issue by swaroopsm** [datocms/js-datocms-client#73]
Hello folks,
The docs for Content Management API (https://www.datocms.com/docs/content-management-api/resources/item/update) mentions on updating the meta fields. I also notice there is an HTTP example for the same.

I tried updating my record using:
```
client.items
  .update(itemId, {
    meta: {
     createdAt: '',
     updatedAt: '',
    }
  })
```
But this doesn't seem to work as expected as I presume the payload body updates only the record fields instead of any meta fields?

Is there a possibility to update meta fields using this library?

Thank you :)

**Comment by matjack1** [comment]
hello @swaroopsm!

you are right about the docs, I'm going to update that now. The problem is that while we allow you to send over the meta fields, we ignore that. We do allow the meta to be sent as a convenience for when you get a record, you update the object and you send it back.

But the meta fields represent an internal state and cannot be changed, sorry!
