### ISSUE TITLE
[Bug]: ApiException in generateClient

### ISSUE THREAD

**Issue by robbielitebit** [datocms/js-datocms-client#89]
I make a request with the SiteClient to update a field. This apparently leads to a 422 `Unprocessable Entity` (no idea why). But the error I receive is:

`TypeError: Cannot read property 'url' of undefined` in `ApiException`

I checked out the library code and this ApiException is thrown in `generateClient`: https://github.com/datocms/js-datocms-client/blob/c103377c869152fa4887228fb79d77326baf9d3b/src/utils/generateClient.js#L164

But here, where this ApiException is thrown, it's missing the third argument for the constructor. And of course that's leading to the TypeError. And now I'm seeing this TypeError instead of the real `Unprocessable Entity` error I should see and that makes debugging a little bit harder :)

**Comment by robbielitebit** [comment]
Found the "real" error btw:

`
{
  code: 'INVALID_FIELD',
  details: {
    field: 'validators.enum',
    code: 'VALIDATION_INVALID',
    message: 'validator not applicable on this field type'
  }
}
`

So it would be very helpful if you receive this instead of the `TypeError`

**Comment by stefanoverna** [comment]
Working on it!

—
Stefano Verna

DatoCMS

--- original message ---
On September 22, 2020, 8:48 AM GMT+2 notifications@github.com wrote:



Found the "real" error btw:

{ code: 'INVALID_FIELD', details: { field: 'validators.enum', code: 'VALIDATION_INVALID', message: 'validator not applicable on this field type' } }

So it would be very helpful if you receive this instead of the TypeError

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by stefanoverna** [comment]
Fixed in v3.0.44, thanks for reporting!

**Comment by robbielitebit** [comment]
> Fixed in v3.0.44, thanks for reporting!

Thanks for the fast fix!
